 ## University Town
 
This code Returns a DataFrame of towns and the states they are in from the university_towns.txt list. The format of the DataFrame should be:DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], columns=["State", "RegionName"]  )
    
The following cleaning needs to be done:

1. For "State", it removes characters from "[" to the end.

2. For "RegionName", when applicable, it removes every character from " (" to the end.

Dataset: 'university_towns.txt'

Source of Dataset: https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 
          'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 
          'OR': 'Oregon','MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 
          'VT': 'Vermont','ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii',
          'WI': 'Wisconsin','MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 
          'GU': 'Guam', 'MS': 'Mississippi','PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 
          'SD': 'South Dakota', 'MP': 'Northern Mariana Islands','IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut',
          'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana',  'KS': 'Kansas', 'NY': 'New York', 
          'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 
          'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota',
          'VI': 'Virgin Islands','NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia',
          'ND': 'North Dakota', 'VA': 'Virginia'}

In [3]:
df=pd.read_table("university_towns.txt",header=None)
df.columns=["data"]
df.head(10)

                                                data
0                                      Alabama[edit]
1                      Auburn (Auburn University)[1]
2             Florence (University of North Alabama)
3    Jacksonville (Jacksonville State University)[2]
4         Livingston (University of West Alabama)[2]
5           Montevallo (University of Montevallo)[2]
6                          Troy (Troy University)[2]
7  Tuscaloosa (University of Alabama, Stillman Co...
8                  Tuskegee (Tuskegee University)[5]
9                                       Alaska[edit]

In [4]:
df.data.head()

0                                      Alabama[edit]
1                      Auburn (Auburn University)[1]
2             Florence (University of North Alabama)
3    Jacksonville (Jacksonville State University)[2]
4         Livingston (University of West Alabama)[2]
Name: data, dtype: object

In [6]:
order_states=np.sort(pd.Series(states).values)
print(order_states)

['Alabama' 'Alaska' 'American Samoa' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'National' 'Nebraska'
 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Northern Mariana Islands' 'Ohio'
 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin'
 'Wyoming']

## Data cleaning, preparation, and organization

In [7]:
NewState=[]
for i in range(0,len(order_states)):
    for j in range(0,len(df.data)):
        if (order_states[i] +'['+'edit'+']'==df.data[j]):
            NewState=np.append(NewState,order_states[i])
print(NewState)

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']

In [8]:
StateRegion=[]
for i in range(0,len(NewState)):
    for j in range(0,len(df.data)):
        if (NewState[i] +'['+'edit'+']'==df.data[j]):
            n = j + 1
    StateRegion=np.append(StateRegion,n)
print(StateRegion)

[  1.  10.  12.  16.  25.  51.  61.  69.  72.  85. 102. 104. 108. 119.
 133. 147. 154. 166. 175. 185. 196. 216. 237. 252. 258. 268. 272. 280.
 283. 291. 302. 308. 340. 359. 362. 385. 397. 408. 452. 455. 467. 472.
 486. 509. 516. 523. 536. 542. 552. 566.]

In [10]:
print(len(StateRegion),len(NewState))

50 50

In [11]:
StateName=[]
CityName=[]
for i in range(0,len(NewState)-1):
    for j in range(0,len(df.data)):
        if (NewState[i] +'['+'edit'+']'==df.data[j]):
            n = j + 1
    while (NewState[i+1] +'['+'edit'+']'!=df.data[n]):
          StateName=np.append(StateName,NewState[i])
          CityName=np.append(CityName,df.data[n])
          n = n + 1
print(StateName)
print(CityName)

['Alabama' 'Alabama' 'Alabama' 'Alabama' 'Alabama' 'Alabama' 'Alabama'
 'Alabama' 'Alaska' 'Arizona' 'Arizona' 'Arizona' 'Arkansas' 'Arkansas'
 'Arkansas' 'Arkansas' 'Arkansas' 'Arkansas' 'Arkansas' 'Arkansas'
 'California' 'California' 'California' 'California' 'California'
 'California' 'California' 'California' 'California' 'California'
 'California' 'California' 'California' 'California' 'California'
 'California' 'California' 'California' 'California' 'California'
 'California' 'California' 'California' 'California' 'California'
 'Colorado' 'Colorado' 'Colorado' 'Colorado' 'Colorado' 'Colorado'
 'Colorado' 'Colorado' 'Colorado' 'Connecticut' 'Connecticut'
 'Connecticut' 'Connecticut' 'Connecticut' 'Connecticut' 'Connecticut'
 'Delaware' 'Delaware' 'Florida' 'Florida' 'Florida' 'Florida' 'Florida'
 'Florida' 'Florida' 'Florida' 'Florida' 'Florida' 'Florida' 'Florida'
 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia'
 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia' 'Georgia'
 'Georgia' 'Georgia' 'Hawaii' 'Idaho' 'Idaho' 'Idaho' 'Illinois'
 'Illinois' 'Illinois' 'Illinois' 'Illinois' 'Illinois' 'Illinois'
 'Illinois' 'Illinois' 'Illinois' 'Indiana' 'Indiana' 'Indiana' 'Indiana'
 'Indiana' 'Indiana' 'Indiana' 'Indiana' 'Indiana' 'Indiana' 'Indiana'
 'Indiana' 'Indiana' 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Iowa'
 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Iowa' 'Kansas' 'Kansas' 'Kansas'
 'Kansas' 'Kansas' 'Kansas' 'Kentucky' 'Kentucky' 'Kentucky' 'Kentucky'
 'Kentucky' 'Kentucky' 'Kentucky' 'Kentucky' 'Kentucky' 'Kentucky'
 'Kentucky' 'Louisiana' 'Louisiana' 'Louisiana' 'Louisiana' 'Louisiana'
 'Louisiana' 'Louisiana' 'Louisiana' 'Maine' 'Maine' 'Maine' 'Maine'
 'Maine' 'Maine' 'Maine' 'Maine' 'Maine' 'Maryland' 'Maryland' 'Maryland'
 'Maryland' 'Maryland' 'Maryland' 'Maryland' 'Maryland' 'Maryland'
 'Maryland' 'Massachusetts' 'Massachusetts' 'Massachusetts'
 'Massachusetts' 'Massachusetts' 'Massachusetts' 'Massachusetts'
 'Massachusetts' 'Massachusetts' 'Massachusetts' 'Massachusetts'
 'Massachusetts' 'Massachusetts' 'Massachusetts' 'Massachusetts'
 'Massachusetts' 'Massachusetts' 'Massachusetts' 'Massachusetts'
 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan'
 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan'
 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan' 'Michigan'
 'Michigan' 'Michigan' 'Minnesota' 'Minnesota' 'Minnesota' 'Minnesota'
 'Minnesota' 'Minnesota' 'Minnesota' 'Minnesota' 'Minnesota' 'Minnesota'
 'Minnesota' 'Minnesota' 'Minnesota' 'Minnesota' 'Mississippi'
 'Mississippi' 'Mississippi' 'Mississippi' 'Mississippi' 'Missouri'
 'Missouri' 'Missouri' 'Missouri' 'Missouri' 'Missouri' 'Missouri'
 'Missouri' 'Missouri' 'Montana' 'Montana' 'Montana' 'Nebraska' 'Nebraska'
 'Nebraska' 'Nebraska' 'Nebraska' 'Nebraska' 'Nebraska' 'Nevada' 'Nevada'
 'New Hampshire' 'New Hampshire' 'New Hampshire' 'New Hampshire'
 'New Hampshire' 'New Hampshire' 'New Hampshire' 'New Jersey' 'New Jersey'
 'New Jersey' 'New Jersey' 'New Jersey' 'New Jersey' 'New Jersey'
 'New Jersey' 'New Jersey' 'New Jersey' 'New Mexico' 'New Mexico'
 'New Mexico' 'New Mexico' 'New Mexico' 'New York' 'New York' 'New York'
 'New York' 'New York' 'New York' 'New York' 'New York' 'New York'
 'New York' 'New York' 'New York' 'New York' 'New York' 'New York'
 'New York' 'New York' 'New York' 'New York' 'New York' 'New York'
 'New York' 'New York' 'New York' 'New York' 'New York' 'New York'
 'New York' 'New York' 'New York' 'New York' 'North Carolina'
 'North Carolina' 'North Carolina' 'North Carolina' 'North Carolina'
 'North Carolina' 'North Carolina' 'North Carolina' 'North Carolina'
 'North Carolina' 'North Carolina' 'North Carolina' 'North Carolina'
 'North Carolina' 'North Carolina' 'North Carolina' 'North Carolina'
 'North Carolina' 'North Dakota' 'North Dakota' 'Ohio' 'Ohio' 'Ohio'
 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio'
 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Ohio' 'Oklahoma'
 'Oklahoma' 'Oklahoma' 'Oklahoma' 'Oklahoma' 'Oklahoma' 'Oklahoma'
 'Oklahoma' 'Oklahoma' 'Oklahoma' 'Oklahoma' 'Oregon' 'Oregon' 'Oregon'
 'Oregon' 'Oregon' 'Oregon' 'Oregon' 'Oregon' 'Oregon' 'Oregon'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Pennsylvania'
 'Pennsylvania' 'Pennsylvania' 'Pennsylvania' 'Rhode Island'
 'Rhode Island' 'South Carolina' 'South Carolina' 'South Carolina'
 'South Carolina' 'South Carolina' 'South Carolina' 'South Carolina'
 'South Carolina' 'South Carolina' 'South Carolina' 'South Carolina'
 'South Dakota' 'South Dakota' 'South Dakota' 'South Dakota' 'Tennessee'
 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee'
 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee' 'Tennessee'
 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas'
 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas' 'Texas'
 'Texas' 'Texas' 'Texas' 'Texas' 'Utah' 'Utah' 'Utah' 'Utah' 'Utah' 'Utah'
 'Vermont' 'Vermont' 'Vermont' 'Vermont' 'Vermont' 'Vermont' 'Virginia'
 'Virginia' 'Virginia' 'Virginia' 'Virginia' 'Virginia' 'Virginia'
 'Virginia' 'Virginia' 'Virginia' 'Virginia' 'Virginia' 'Washington'
 'Washington' 'Washington' 'Washington' 'Washington' 'West Virginia'
 'West Virginia' 'West Virginia' 'West Virginia' 'West Virginia'
 'West Virginia' 'West Virginia' 'West Virginia' 'West Virginia'
 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin'
 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin' 'Wisconsin'
 'Wisconsin']
['Auburn (Auburn University)[1]' 'Florence (University of North Alabama)'
 'Jacksonville (Jacksonville State University)[2]'
 'Livingston (University of West Alabama)[2]'
 'Montevallo (University of Montevallo)[2]' 'Troy (Troy University)[2]'
 'Tuscaloosa (University of Alabama, Stillman College, Shelton State)[3][4]'
 'Tuskegee (Tuskegee University)[5]'
 'Fairbanks (University of Alaska Fairbanks)[2]'
 'Flagstaff (Northern Arizona University)[6]'
 'Tempe (Arizona State University)' 'Tucson (University of Arizona)'
 'Arkadelphia (Henderson State University, Ouachita Baptist University)[2]'
 'Conway (Central Baptist College, Hendrix College, University of Central Arkansas)[2]'
 'Fayetteville (University of Arkansas)[7]'
 'Jonesboro (Arkansas State University)[8]'
 'Magnolia (Southern Arkansas University)[2]'
 'Monticello (University of Arkansas at Monticello)[2]'
 'Russellville (Arkansas Tech University)[2]'
 'Searcy (Harding University)[5]' 'Angwin (Pacific Union College)[2]'
 'Arcata (Humboldt State University)[5]'
 'Berkeley (University of California, Berkeley)[5]'
 'Chico (California State University, Chico)[2]'
 'Claremont (Claremont McKenna College, Pomona College, Harvey Mudd College, Scripps College, Pitzer College, Keck Graduate Institute, Claremont Graduate University)[5]'
 'Cotati (California State University, Sonoma)[2]'
 'Davis (University of California, Davis)[1]'
 'Irvine (University of California, Irvine)'
 'Isla Vista (University of California, Santa Barbara)[2]'
 'University Park, Los Angeles (University of Southern California)'
 'Merced (University of California, Merced)' 'Orange (Chapman University)'
 'Palo Alto (Stanford University)'
 'Pomona (Cal Poly Pomona, WesternU)[9][10][11] and formerly Pomona College'
 'Redlands (University of Redlands)'
 'Riverside (University of California, Riverside, California Baptist University, La Sierra University)'
 'Sacramento (California State University, Sacramento)'
 'University District, San Bernardino (California State University, San Bernardino, American Sports University)'
 'San Diego (University of California, San Diego, San Diego State University)'
 'San Luis Obispo (California Polytechnic State University)[2]'
 'Santa Barbara (Fielding Graduate University, Santa Barbara City College, University of California, Santa Barbara, Westmont College)[2]'
 'Santa Cruz (University of California, Santa Cruz)[2]'
 'Turlock (California State University, Stanislaus)'
 'Westwood, Los Angeles (University of California, Los Angeles)[2]'
 'Whittier (Whittier CollegeRio Hondo College)'
 'Alamosa (Adams State College)[2]'
 'Boulder (University of Colorado at Boulder)[12]'
 'Durango (Fort Lewis College)[2]'
 'Fort Collins (Colorado State University)[13]'
 'Golden (Colorado School of Mines)'
 'Grand Junction (Colorado Mesa University)'
 'Greeley (University of Northern Colorado)'
 'Gunnison (Western State College)[2]'
 'Pueblo, Colorado (Colorado State University-Pueblo)'
 'Fairfield (Fairfield University, Sacred Heart University)'
 'Middletown (Wesleyan University)'
 'New Britain (Central Connecticut State University)'
 'New Haven (Yale University, University of New Haven, Southern Connecticut State University, Albertus Magnus College, Quinnipiac University)[14]'
 'New London (Connecticut College, US Coast Guard Academy, Mitchell College)[2]'
 'Storrs (University of Connecticut)[2]'
 'Willimantic (Eastern Connecticut State University)[2]'
 'Dover (Delaware State University)[1]'
 'Newark (University of Delaware)[1]' 'Ave Maria (Ave Maria University)'
 'Boca Raton (Florida Atlantic University)'
 'Coral Gables (University of Miami)' 'DeLand (Stetson University)[5]'
 'Estero (Florida Gulf Coast University)'
 'Gainesville (University of Florida, Santa Fe College)'
 'Orlando (University of Central Florida)'
 'Sarasota (New College of Florida, Ringling College of Art and Design, State College of Florida, Manatee-Sarasota, University of South Florida Sarasota-Manatee)'
 'St. Augustine (Flagler College)' 'St. Leo (St. Leo University)'
 'Tallahassee (Florida State University, Florida A&M University)'
 'Tampa (University of South Florida)' 'Albany (Albany State University)'
 'Athens (University of Georgia)[15]'
 'Atlanta (Georgia State University, Georgia Tech, Emory)[2]'
 'Carrollton (University of West Georgia)[2]*Dahlonega (North Georgia College & State University)[2]'
 'Demorest (Piedmont College)[2]'
 'Fort Valley (Fort Valley State University)[2]'
 'Kennesaw (Kennesaw State University)'
 'Milledgeville (Georgia College & State University)[2]'
 'Mount Vernon (Brewton-Parker College)[2]' 'Oxford (Oxford College)'
 'Rome (Berry College, Shorter University)'
 'Savannah (Armstrong Atlantic State University, Savannah State University, Savannah College of Art and Design)'
 'Statesboro (Georgia Southern University)[5]'
 'Valdosta (Valdosta State University)[2]'
 'Waleska (Reinhardt College)[2]' 'Young Harris (Young Harris College)[2]'
 'Manoa (University of Hawaii at Manoa)[2]'
 'Moscow (University of Idaho)[2]' 'Pocatello (Idaho State University)[2]'
 'Rexburg (BYU-Idaho)[2]'
 'Carbondale (Southern Illinois University Carbondale)[5]'
 'Champaign–Urbana (University of Illinois at Urbana–Champaign)[5]'
 'Charleston (Eastern Illinois University)[2]'
 'DeKalb (Northern Illinois University)[2]'
 'Edwardsville (Southern Illinois University Edwardsville)[2]'
 'Evanston (Northwestern University)[2]'
 'Lebanon (McKendree University)[2]'
 'Macomb (Western Illinois University)[2]'
 'Normal (Illinois State University)[2]' 'Peoria (Bradley University)'
 'Bloomington (Indiana University Bloomington)[5]'
 'Crawfordsville (Wabash College)' 'Greencastle (DePauw University)[5]'
 'Hanover (Hanover College)[2]' 'Marion (Indiana Wesleyan University)[2]'
 'Muncie (Ball State University)[2]'
 'Oakland City (Oakland City University)[2]'
 'Richmond (Earlham College)[2]' 'South Bend (Notre Dame University[2])'
 'Terre Haute (Indiana State University, Rose-Hulman Institute of Technology)[2]'
 'Upland (Taylor University)[2]' 'Valparaiso (Valparaiso University)'
 'West Lafayette (Purdue University)[2]' 'Ames (Iowa State University)[2]'
 'Cedar Falls (University of Northern Iowa)[2]'
 'Cedar Rapids, Iowa (Coe College )' 'Decorah (Luther College)[5]'
 'Fayette (Upper Iowa University)[2]' 'Grinnell (Grinnell College)[15]'
 'Iowa City (University of Iowa)[15]' 'Lamoni (Graceland University)[2]'
 'Mount Vernon, (Cornell College)' 'Orange City (Northwestern College)[2]'
 'Sioux Center (Dordt College)[2]'
 'Storm Lake (Buena Vista University)[2]' 'Waverly (Wartburg College)[2]'
 'Baldwin City (Baker University)[5]'
 'Emporia (Emporia State University)[2]'
 'Hays (Fort Hays State University)[2]'
 'Lawrence (University of Kansas, Haskell Indian Nations University)[15]'
 'Manhattan (Kansas State University, Manhattan Christian College)[15]'
 'Pittsburg (Pittsburg State University)[2]'
 'Bowling Green (Western Kentucky University)[2]'
 'Columbia (Lindsey Wilson College)[2]' 'Georgetown (Georgetown College)'
 'Highland Heights (Northern Kentucky University)'
 'Lexington (University of Kentucky, Transylvania University[5]'
 'Louisville (University of Louisville)'
 'Morehead (Morehead State University)[2]'
 'Murray (Murray State University)[5]'
 'Richmond (Eastern Kentucky University)[2]'
 'Williamsburg (University of the Cumberlands)[2]'
 'Wilmore (Asbury University, Asbury Theological Seminary)[2]'
 'Baton Rouge (Louisiana State University, Southern University)'
 'Grambling (Grambling State University)[5]'
 'Hammond (Southeastern Louisiana University)[2]'
 'Lafayette (University of Louisiana at Lafayette)'
 'Monroe (University of Louisiana at Monroe)[2]'
 'Natchitoches (Northwestern State University)[2]'
 'Ruston (Louisiana Tech University)[2]'
 'Thibodaux (Nicholls State University)[2]'
 'Augusta (University of Maine at Augusta)[2]'
 'Bar Harbor (College of the Atlantic)' 'Brunswick (Bowdoin College)'
 'Farmington (University of Maine at Farmington)[2]'
 'Fort Kent (University of Maine at Fort Kent)'
 'Gorham (University of Southern Maine)[2]'
 'Lewiston, Maine (Bates College)' 'Orono (University of Maine)[2]'
 'Waterville (Thomas College, Colby College)'
 "Annapolis (United States Naval Academy, St. John's College)"
 'Chestertown (Washington College)[2]'
 'College Park (University of Maryland, College Park)[16]'
 'Cumberland (Allegany College of Maryland)'
 "Emmitsburg (Mount St. Mary's University)[2]"
 'Frostburg (Frostburg State University)[5]'
 'Princess Anne (University of Maryland Eastern Shore)[5]'
 'Towson (Towson University, Goucher College)[2]'
 'Salisbury (Salisbury University)[2]' 'Westminster (McDaniel College)'
 'Boston (Boston University, Boston College, Boston Conservatory, New England Conservatory, Brandeis University, Northeastern University, UMass Boston, Emmanuel College, Bunker Hill Community College, Roxbury Community College, Suffolk University, Simmons College, among many others)'
 'Bridgewater (Bridgewater State College)[2]'
 'Cambridge (Harvard University, Massachusetts Institute of Technology)(Lesley University, Cambridge College, Longy School of Music)[15]'
 'Chestnut Hill (Boston College)' 'The Colleges of Worcester Consortium:'
 'Dudley (Nichols College)'
 'North Grafton (Cummings School of Veterinary Medicine at Tufts University)'
 'Paxton (Anna Maria College)'
 'Worcester (Assumption, Becker, Clark University, Holy Cross, Mass. College of Pharmacy & Health Sciences, Quinsigamond Community College, UMass Medical School, Worcester State University, Worcester Polytechnic Institute)'
 'The Five College Region of Western Massachusetts:'
 'Amherst (Amherst College, Hampshire College, University of Massachusetts Amherst)[15]'
 'Northampton (Smith College)' 'South Hadley (Mount Holyoke College)'
 'Fitchburg (Fitchburg State College)'
 'North Adams (Massachusetts College of Liberal Arts)'
 'Springfield (American International College), (Springfield College), and (Western New England College)'
 'Waltham (Bentley University), (Brandeis University)'
 'Williamstown (Williams College)'
 'Framingham (Framingham State University)'
 'Adrian (Adrian College, Siena Heights University)'
 'Albion (Albion College)[17]' 'Allendale (Grand Valley State University)'
 'Alma (Alma College)' 'Ann Arbor (University of Michigan)[1]'
 'Berrien Springs (Andrews University)[2]'
 'Big Rapids (Ferris State University)[2]'
 'East Lansing (Michigan State University)[2]'
 'Flint (Kettering University, University of Michigan-Flint)'
 'Hillsdale (Hillsdale College)'
 'Houghton (Michigan Technological University)[5]'
 'Kalamazoo (Western Michigan University, Kalamazoo College)[2]'
 'Marquette (Northern Michigan University)[2]'
 'Midland (Northwood University)'
 'Mount Pleasant (Central Michigan University)[2]'
 'Olivet (Olivet College)[2]' 'Saginaw (Saginaw Valley State University)'
 'Sault Ste. Marie (Lake Superior State University)'
 'Spring Arbor (Spring Arbor University)[2]'
 'Ypsilanti (Eastern Michigan University)[2]'
 'Bemidji (Bemidji State University)[2]'
 'Crookston (University of Minnesota Crookston)[2]'
 'Duluth (University of Minnesota Duluth, Lake Superior College, The College of St. Scholastica, University of Wisconsin–Superior, Duluth Business University'
 'Faribault, South Central College'
 'Mankato (Minnesota State University, Mankato),[2] Bethany Lutheran College'
 'Marshall (Southwest Minnesota State University)[2]'
 'Moorhead (Minnesota State University, Moorhead, Concordia College)[18]'
 'Morris (University of Minnesota Morris)[2]'
 'Northfield (Carleton College, St. Olaf College)[5]'
 'North Mankato, South Central College'
 'St. Cloud (St. Cloud State University, The College of St. Scholastica)[2]'
 'St. Joseph (College of Saint Benedict)[2]'
 'St. Peter (Gustavus Adolphus College)[2]'
 "Winona (Winona State University, St. Mary's University of Minnesota)[19]"
 'Cleveland (Delta State University)[2]'
 'Hattiesburg (University of Southern Mississippi)[20]'
 'Itta Bena (Mississippi Valley State University)[2]'
 'Oxford (University of Mississippi)[2]'
 'Starkville (Mississippi State University)[2]'
 'Bolivar (Southwest Baptist University)[2]'
 'Cape Girardeau (Southeast Missouri State University)[2]'
 'Columbia (University of Missouri, Stephens College, Columbia College)[20]'
 'Fayette (Central Methodist University)[2]'
 'Fulton (Westminster College and William Woods University).'
 'Kirksville (Truman State University, A. T. Still University)[2]'
 'Maryville (Northwest Missouri State University)[2]'
 'Rolla (Missouri University of Science and Technology)[2]'
 'Warrensburg (University of Central Missouri)[5]'
 'Bozeman (Montana State University)[2]'
 'Dillon (University of Montana Western)[2]'
 'Missoula (University of Montana)[5]'
 'Chadron (Chadron State College)[5]' 'Crete (Doane College)[2]'
 'Kearney (University of Nebraska at Kearney)[2]'
 'Lincoln (University of Nebraska at Lincoln)[5]'
 'Peru (Peru State College)[2]' 'Seward (Concordia University)[2]'
 'Wayne (Wayne State College)[2]'
 'Las Vegas (University of Nevada, Las Vegas)'
 'Reno (University of Nevada, Reno)'
 'New London, New Hampshire (Colby-Sawyer College)'
 'Durham (University of New Hampshire)[2]'
 'Hanover (Dartmouth College)[5]' 'Henniker (New England College)'
 'Keene (Keene State College)[2]'
 'Plymouth (Plymouth State University)[2]'
 'Rindge (Franklin Pierce University)'
 'Ewing (The College of New Jersey), (Rider University)'
 "Jersey City (New Jersey City University), (Saint Peter's University)"
 'Glassboro (Rowan University)[2]'
 'Hoboken (Stevens Institute of Technology)'
 'Madison (Drew University), (Fairleigh Dickinson University), (College of Saint Elizabeth)'
 'Newark (Rutgers University), (New Jersey Institute of Technology), (UMDNJ)'
 'New Brunswick (Rutgers University)[5]'

In [12]:
print(pd.DataFrame(StateName,CityName))

                                                            0
Auburn (Auburn University)[1]                         Alabama
Florence (University of North Alabama)                Alabama
Jacksonville (Jacksonville State University)[2]       Alabama
Livingston (University of West Alabama)[2]            Alabama
Montevallo (University of Montevallo)[2]              Alabama
...                                                       ...
Platteville (University of Wisconsin–Plattevill...  Wisconsin
River Falls (University of Wisconsin–River Fall...  Wisconsin
Stevens Point (University of Wisconsin–Stevens ...  Wisconsin
Waukesha (Carroll University)                       Wisconsin
Whitewater (University of Wisconsin–Whitewater)[2]  Wisconsin

[516 rows x 1 columns]

In [14]:
CTYNAME=[]
for i in CityName:
    CTYNAME=np.append(CTYNAME, i.split('(')[0])
print(CTYNAME)

['Auburn ' 'Florence ' 'Jacksonville ' 'Livingston ' 'Montevallo ' 'Troy '
 'Tuscaloosa ' 'Tuskegee ' 'Fairbanks ' 'Flagstaff ' 'Tempe ' 'Tucson '
 'Arkadelphia ' 'Conway ' 'Fayetteville ' 'Jonesboro ' 'Magnolia '
 'Monticello ' 'Russellville ' 'Searcy ' 'Angwin ' 'Arcata ' 'Berkeley '
 'Chico ' 'Claremont ' 'Cotati ' 'Davis ' 'Irvine ' 'Isla Vista '
 'University Park, Los Angeles ' 'Merced ' 'Orange ' 'Palo Alto '
 'Pomona ' 'Redlands ' 'Riverside ' 'Sacramento '
 'University District, San Bernardino ' 'San Diego ' 'San Luis Obispo '
 'Santa Barbara ' 'Santa Cruz ' 'Turlock ' 'Westwood, Los Angeles '
 'Whittier ' 'Alamosa ' 'Boulder ' 'Durango ' 'Fort Collins ' 'Golden '
 'Grand Junction ' 'Greeley ' 'Gunnison ' 'Pueblo, Colorado ' 'Fairfield '
 'Middletown ' 'New Britain ' 'New Haven ' 'New London ' 'Storrs '
 'Willimantic ' 'Dover ' 'Newark ' 'Ave Maria ' 'Boca Raton '
 'Coral Gables ' 'DeLand ' 'Estero ' 'Gainesville ' 'Orlando ' 'Sarasota '
 'St. Augustine ' 'St. Leo ' 'Tallahassee ' 'Tampa ' 'Albany ' 'Athens '
 'Atlanta ' 'Carrollton ' 'Demorest ' 'Fort Valley ' 'Kennesaw '
 'Milledgeville ' 'Mount Vernon ' 'Oxford ' 'Rome ' 'Savannah '
 'Statesboro ' 'Valdosta ' 'Waleska ' 'Young Harris ' 'Manoa ' 'Moscow '
 'Pocatello ' 'Rexburg ' 'Carbondale ' 'Champaign–Urbana ' 'Charleston '
 'DeKalb ' 'Edwardsville ' 'Evanston ' 'Lebanon ' 'Macomb ' 'Normal '
 'Peoria ' 'Bloomington ' 'Crawfordsville ' 'Greencastle ' 'Hanover '
 'Marion ' 'Muncie ' 'Oakland City ' 'Richmond ' 'South Bend '
 'Terre Haute ' 'Upland ' 'Valparaiso ' 'West Lafayette ' 'Ames '
 'Cedar Falls ' 'Cedar Rapids, Iowa ' 'Decorah ' 'Fayette ' 'Grinnell '
 'Iowa City ' 'Lamoni ' 'Mount Vernon, ' 'Orange City ' 'Sioux Center '
 'Storm Lake ' 'Waverly ' 'Baldwin City ' 'Emporia ' 'Hays ' 'Lawrence '
 'Manhattan ' 'Pittsburg ' 'Bowling Green ' 'Columbia ' 'Georgetown '
 'Highland Heights ' 'Lexington ' 'Louisville ' 'Morehead ' 'Murray '
 'Richmond ' 'Williamsburg ' 'Wilmore ' 'Baton Rouge ' 'Grambling '
 'Hammond ' 'Lafayette ' 'Monroe ' 'Natchitoches ' 'Ruston ' 'Thibodaux '
 'Augusta ' 'Bar Harbor ' 'Brunswick ' 'Farmington ' 'Fort Kent '
 'Gorham ' 'Lewiston, Maine ' 'Orono ' 'Waterville ' 'Annapolis '
 'Chestertown ' 'College Park ' 'Cumberland ' 'Emmitsburg ' 'Frostburg '
 'Princess Anne ' 'Towson ' 'Salisbury ' 'Westminster ' 'Boston '
 'Bridgewater ' 'Cambridge ' 'Chestnut Hill '
 'The Colleges of Worcester Consortium:' 'Dudley ' 'North Grafton '
 'Paxton ' 'Worcester '
 'The Five College Region of Western Massachusetts:' 'Amherst '
 'Northampton ' 'South Hadley ' 'Fitchburg ' 'North Adams ' 'Springfield '
 'Waltham ' 'Williamstown ' 'Framingham ' 'Adrian ' 'Albion ' 'Allendale '
 'Alma ' 'Ann Arbor ' 'Berrien Springs ' 'Big Rapids ' 'East Lansing '
 'Flint ' 'Hillsdale ' 'Houghton ' 'Kalamazoo ' 'Marquette ' 'Midland '
 'Mount Pleasant ' 'Olivet ' 'Saginaw ' 'Sault Ste. Marie '
 'Spring Arbor ' 'Ypsilanti ' 'Bemidji ' 'Crookston ' 'Duluth '
 'Faribault, South Central College' 'Mankato ' 'Marshall ' 'Moorhead '
 'Morris ' 'Northfield ' 'North Mankato, South Central College'
 'St. Cloud ' 'St. Joseph ' 'St. Peter ' 'Winona ' 'Cleveland '
 'Hattiesburg ' 'Itta Bena ' 'Oxford ' 'Starkville ' 'Bolivar '
 'Cape Girardeau ' 'Columbia ' 'Fayette ' 'Fulton ' 'Kirksville '
 'Maryville ' 'Rolla ' 'Warrensburg ' 'Bozeman ' 'Dillon ' 'Missoula '
 'Chadron ' 'Crete ' 'Kearney ' 'Lincoln ' 'Peru ' 'Seward ' 'Wayne '
 'Las Vegas ' 'Reno ' 'New London, New Hampshire ' 'Durham ' 'Hanover '
 'Henniker ' 'Keene ' 'Plymouth ' 'Rindge ' 'Ewing ' 'Jersey City '
 'Glassboro ' 'Hoboken ' 'Madison ' 'Newark ' 'New Brunswick '
 'Princeton ' 'Union ' 'West Long Branch ' 'Hobbs ' 'Las Cruces '
 'Las Vegas ' 'Portales ' 'Silver City ' 'Alfred ' 'Albany ' 'Aurora '
 'Binghamton ' 'Brockport ' 'Buffalo ' 'Canton ' 'Clinton ' 'Cobleskill '
 'Delhi ' 'Fredonia ' 'Geneseo ' 'Geneva ' 'Hamilton ' 'Ithaca '
 'Morningside Heights, Manhattan ' 'New Paltz ' 'Oneonta ' 'Oswego '
 'Plattsburgh ' 'Potsdam ' 'Poughkeepsie ' 'Purchase ' 'Rochester '
 'Saratoga Springs ' 'Seneca Falls ' 'Stony Brook ' 'Syracuse ' 'Tivoli '
 'Troy ' 'West Point ' 'Banner Elk ' 'Boiling Springs ' 'Boone '
 'Buies Creek ' 'Chapel Hill ' 'Cullowhee ' 'Davidson ' 'Durham ' 'Elon '
 'Greensboro ' 'Greenville ' 'Hickory ' 'Mars Hill ' 'Mount Olive '
 'Pembroke ' 'Wilmington, North Carolina ' 'Wingate ' 'Winston-Salem '
 'Fargo ' 'Grand Forks ' 'Ada ' 'Alliance ' 'Ashland ' 'Athens ' 'Berea '
 'Bluffton ' 'Bowling Green ' 'Cedarville ' 'Columbus ' 'Delaware '
 'Fairborn ' 'Findlay ' 'Gambier ' 'Granville ' 'Hiram ' 'Kent '
 'Nelsonville ' 'New Concord ' 'Oberlin ' 'Oxford ' 'Rio Grande '
 'Wilberforce ' 'Ada ' 'Alva ' 'Durant ' 'Edmond ' 'Goodwell ' 'Langston '
 'Norman ' 'Stillwater ' 'Tahlequah ' 'Tulsa ' 'Weatherford ' 'Ashland '
 'Corvallis ' 'Eugene ' 'Forest Grove ' 'Klamath Falls ' 'La Grande '
 'Marylhurst ' 'McMinnville ' 'Monmouth ' 'Newberg ' 'Altoona '
 'Annville ' 'Bethlehem ' 'Bloomsburg ' 'Bradford ' 'California '
 'Carlisle ' 'Cecil B. Moore, Philadelphia, also known as "Templetown" '
 'Clarion ' 'Collegeville ' 'Cresson ' 'East Stroudsburg ' 'Edinboro '
 'Erie ' 'Gettysburg ' 'Greensburg ' 'Grove City ' 'Huntingdon '
 'Indiana ' 'Johnstown ' 'Kutztown ' 'Lancaster ' 'Lewisburg '
 'Lock Haven ' 'Loretto ' 'Mansfield ' 'Meadville ' 'Mont Alto '
 'Millersville ' 'New Wilmington ' 'North East '
 'University City, Philadelphia ' 'Oakland, Pittsburgh ' 'Reading '
 'Selinsgrove ' 'Shippensburg ' 'Slippery Rock ' 'State College '
 'Villanova ' 'Waynesburg ' 'West Chester ' 'Wilkes-Barre '
 'Williamsport ' 'Kingston ' 'Providence ' 'Central ' 'Charleston '
 'Clemson ' 'Clinton ' 'Columbia ' 'Due West ' 'Florence ' 'Greenwood '
 'Orangeburg ' 'Rock Hill ' 'Spartanburg ' 'Brookings ' 'Madison '
 'Spearfish ' 'Vermillion ' 'Chattanooga ' 'Collegedale ' 'Cookeville '
 'Harrogate ' 'Henderson ' 'Johnson City ' 'Knoxville ' 'Martin '
 'McKenzie ' 'Memphis ' 'Murfreesboro ' 'Nashville ' 'Sewanee ' 'Abilene '
 'Alpine ' 'Austin ' 'Beaumont ' 'Canyon ' 'College Station ' 'Commerce '
 'Dallas ' 'Denton ' 'Fort Worth ' 'Georgetown ' 'Huntsville ' 'Houston '
 'Keene ' 'Kingsville ' 'Lubbock ' 'Nacogdoches ' 'Plainview '
 'Prairie View ' 'San Marcos ' 'Stephenville ' 'Waco ' 'Cedar City '
 'Logan ' 'Provo ' 'Orem ' 'Salt Lake City ' 'Ephraim ' 'Burlington '
 'Castleton ' 'Johnson ' 'Lyndonville ' 'Middlebury ' 'Northfield '
 'Blacksburg ' 'Bridgewater ' 'Charlottesville ' 'Farmville '
 'Fredericksburg ' 'Harrisonburg ' 'Lexington ' 'Lynchburg ' 'Radford '
 'Williamsburg ' 'Wise ' 'Chesapeake ' 'Bellingham ' 'Cheney '
 'Ellensburg ' 'Pullman ' 'University District, Seattle ' 'Athens '
 'Buckhannon ' 'Fairmont ' 'Glenville ' 'Huntington ' 'Montgomery '
 'Morgantown ' 'Shepherdstown ' 'West Liberty ' 'Appleton ' 'Eau Claire '
 'Green Bay ' 'La Crosse ' 'Madison ' 'Menomonie ' 'Milwaukee ' 'Oshkosh '
 'Platteville ' 'River Falls ' 'Stevens Point ' 'Waukesha ' 'Whitewater ']

In [15]:
city_new=[]
for i in CTYNAME:
    if i[-1]==' ':
        city_new = np.append(city_new,i[:-1])
    else:
        city_new=np.append(city_new,i) 
print(city_new)

['Auburn' 'Florence' 'Jacksonville' 'Livingston' 'Montevallo' 'Troy'
 'Tuscaloosa' 'Tuskegee' 'Fairbanks' 'Flagstaff' 'Tempe' 'Tucson'
 'Arkadelphia' 'Conway' 'Fayetteville' 'Jonesboro' 'Magnolia' 'Monticello'
 'Russellville' 'Searcy' 'Angwin' 'Arcata' 'Berkeley' 'Chico' 'Claremont'
 'Cotati' 'Davis' 'Irvine' 'Isla Vista' 'University Park, Los Angeles'
 'Merced' 'Orange' 'Palo Alto' 'Pomona' 'Redlands' 'Riverside'
 'Sacramento' 'University District, San Bernardino' 'San Diego'
 'San Luis Obispo' 'Santa Barbara' 'Santa Cruz' 'Turlock'
 'Westwood, Los Angeles' 'Whittier' 'Alamosa' 'Boulder' 'Durango'
 'Fort Collins' 'Golden' 'Grand Junction' 'Greeley' 'Gunnison'
 'Pueblo, Colorado' 'Fairfield' 'Middletown' 'New Britain' 'New Haven'
 'New London' 'Storrs' 'Willimantic' 'Dover' 'Newark' 'Ave Maria'
 'Boca Raton' 'Coral Gables' 'DeLand' 'Estero' 'Gainesville' 'Orlando'
 'Sarasota' 'St. Augustine' 'St. Leo' 'Tallahassee' 'Tampa' 'Albany'
 'Athens' 'Atlanta' 'Carrollton' 'Demorest' 'Fort Valley' 'Kennesaw'
 'Milledgeville' 'Mount Vernon' 'Oxford' 'Rome' 'Savannah' 'Statesboro'
 'Valdosta' 'Waleska' 'Young Harris' 'Manoa' 'Moscow' 'Pocatello'
 'Rexburg' 'Carbondale' 'Champaign–Urbana' 'Charleston' 'DeKalb'
 'Edwardsville' 'Evanston' 'Lebanon' 'Macomb' 'Normal' 'Peoria'
 'Bloomington' 'Crawfordsville' 'Greencastle' 'Hanover' 'Marion' 'Muncie'
 'Oakland City' 'Richmond' 'South Bend' 'Terre Haute' 'Upland'
 'Valparaiso' 'West Lafayette' 'Ames' 'Cedar Falls' 'Cedar Rapids, Iowa'
 'Decorah' 'Fayette' 'Grinnell' 'Iowa City' 'Lamoni' 'Mount Vernon,'
 'Orange City' 'Sioux Center' 'Storm Lake' 'Waverly' 'Baldwin City'
 'Emporia' 'Hays' 'Lawrence' 'Manhattan' 'Pittsburg' 'Bowling Green'
 'Columbia' 'Georgetown' 'Highland Heights' 'Lexington' 'Louisville'
 'Morehead' 'Murray' 'Richmond' 'Williamsburg' 'Wilmore' 'Baton Rouge'
 'Grambling' 'Hammond' 'Lafayette' 'Monroe' 'Natchitoches' 'Ruston'
 'Thibodaux' 'Augusta' 'Bar Harbor' 'Brunswick' 'Farmington' 'Fort Kent'
 'Gorham' 'Lewiston, Maine' 'Orono' 'Waterville' 'Annapolis' 'Chestertown'
 'College Park' 'Cumberland' 'Emmitsburg' 'Frostburg' 'Princess Anne'
 'Towson' 'Salisbury' 'Westminster' 'Boston' 'Bridgewater' 'Cambridge'
 'Chestnut Hill' 'The Colleges of Worcester Consortium:' 'Dudley'
 'North Grafton' 'Paxton' 'Worcester'
 'The Five College Region of Western Massachusetts:' 'Amherst'
 'Northampton' 'South Hadley' 'Fitchburg' 'North Adams' 'Springfield'
 'Waltham' 'Williamstown' 'Framingham' 'Adrian' 'Albion' 'Allendale'
 'Alma' 'Ann Arbor' 'Berrien Springs' 'Big Rapids' 'East Lansing' 'Flint'
 'Hillsdale' 'Houghton' 'Kalamazoo' 'Marquette' 'Midland' 'Mount Pleasant'
 'Olivet' 'Saginaw' 'Sault Ste. Marie' 'Spring Arbor' 'Ypsilanti'
 'Bemidji' 'Crookston' 'Duluth' 'Faribault, South Central College'
 'Mankato' 'Marshall' 'Moorhead' 'Morris' 'Northfield'
 'North Mankato, South Central College' 'St. Cloud' 'St. Joseph'
 'St. Peter' 'Winona' 'Cleveland' 'Hattiesburg' 'Itta Bena' 'Oxford'
 'Starkville' 'Bolivar' 'Cape Girardeau' 'Columbia' 'Fayette' 'Fulton'
 'Kirksville' 'Maryville' 'Rolla' 'Warrensburg' 'Bozeman' 'Dillon'
 'Missoula' 'Chadron' 'Crete' 'Kearney' 'Lincoln' 'Peru' 'Seward' 'Wayne'
 'Las Vegas' 'Reno' 'New London, New Hampshire' 'Durham' 'Hanover'
 'Henniker' 'Keene' 'Plymouth' 'Rindge' 'Ewing' 'Jersey City' 'Glassboro'
 'Hoboken' 'Madison' 'Newark' 'New Brunswick' 'Princeton' 'Union'
 'West Long Branch' 'Hobbs' 'Las Cruces' 'Las Vegas' 'Portales'
 'Silver City' 'Alfred' 'Albany' 'Aurora' 'Binghamton' 'Brockport'
 'Buffalo' 'Canton' 'Clinton' 'Cobleskill' 'Delhi' 'Fredonia' 'Geneseo'
 'Geneva' 'Hamilton' 'Ithaca' 'Morningside Heights, Manhattan' 'New Paltz'
 'Oneonta' 'Oswego' 'Plattsburgh' 'Potsdam' 'Poughkeepsie' 'Purchase'
 'Rochester' 'Saratoga Springs' 'Seneca Falls' 'Stony Brook' 'Syracuse'
 'Tivoli' 'Troy' 'West Point' 'Banner Elk' 'Boiling Springs' 'Boone'
 'Buies Creek' 'Chapel Hill' 'Cullowhee' 'Davidson' 'Durham' 'Elon'
 'Greensboro' 'Greenville' 'Hickory' 'Mars Hill' 'Mount Olive' 'Pembroke'
 'Wilmington, North Carolina' 'Wingate' 'Winston-Salem' 'Fargo'
 'Grand Forks' 'Ada' 'Alliance' 'Ashland' 'Athens' 'Berea' 'Bluffton'
 'Bowling Green' 'Cedarville' 'Columbus' 'Delaware' 'Fairborn' 'Findlay'
 'Gambier' 'Granville' 'Hiram' 'Kent' 'Nelsonville' 'New Concord'
 'Oberlin' 'Oxford' 'Rio Grande' 'Wilberforce' 'Ada' 'Alva' 'Durant'
 'Edmond' 'Goodwell' 'Langston' 'Norman' 'Stillwater' 'Tahlequah' 'Tulsa'
 'Weatherford' 'Ashland' 'Corvallis' 'Eugene' 'Forest Grove'
 'Klamath Falls' 'La Grande' 'Marylhurst' 'McMinnville' 'Monmouth'
 'Newberg' 'Altoona' 'Annville' 'Bethlehem' 'Bloomsburg' 'Bradford'
 'California' 'Carlisle'
 'Cecil B. Moore, Philadelphia, also known as "Templetown"' 'Clarion'
 'Collegeville' 'Cresson' 'East Stroudsburg' 'Edinboro' 'Erie'
 'Gettysburg' 'Greensburg' 'Grove City' 'Huntingdon' 'Indiana' 'Johnstown'
 'Kutztown' 'Lancaster' 'Lewisburg' 'Lock Haven' 'Loretto' 'Mansfield'
 'Meadville' 'Mont Alto' 'Millersville' 'New Wilmington' 'North East'
 'University City, Philadelphia' 'Oakland, Pittsburgh' 'Reading'
 'Selinsgrove' 'Shippensburg' 'Slippery Rock' 'State College' 'Villanova'
 'Waynesburg' 'West Chester' 'Wilkes-Barre' 'Williamsport' 'Kingston'
 'Providence' 'Central' 'Charleston' 'Clemson' 'Clinton' 'Columbia'
 'Due West' 'Florence' 'Greenwood' 'Orangeburg' 'Rock Hill' 'Spartanburg'
 'Brookings' 'Madison' 'Spearfish' 'Vermillion' 'Chattanooga'
 'Collegedale' 'Cookeville' 'Harrogate' 'Henderson' 'Johnson City'
 'Knoxville' 'Martin' 'McKenzie' 'Memphis' 'Murfreesboro' 'Nashville'
 'Sewanee' 'Abilene' 'Alpine' 'Austin' 'Beaumont' 'Canyon'
 'College Station' 'Commerce' 'Dallas' 'Denton' 'Fort Worth' 'Georgetown'
 'Huntsville' 'Houston' 'Keene' 'Kingsville' 'Lubbock' 'Nacogdoches'
 'Plainview' 'Prairie View' 'San Marcos' 'Stephenville' 'Waco'
 'Cedar City' 'Logan' 'Provo' 'Orem' 'Salt Lake City' 'Ephraim'
 'Burlington' 'Castleton' 'Johnson' 'Lyndonville' 'Middlebury'
 'Northfield' 'Blacksburg' 'Bridgewater' 'Charlottesville' 'Farmville'
 'Fredericksburg' 'Harrisonburg' 'Lexington' 'Lynchburg' 'Radford'
 'Williamsburg' 'Wise' 'Chesapeake' 'Bellingham' 'Cheney' 'Ellensburg'
 'Pullman' 'University District, Seattle' 'Athens' 'Buckhannon' 'Fairmont'
 'Glenville' 'Huntington' 'Montgomery' 'Morgantown' 'Shepherdstown'
 'West Liberty' 'Appleton' 'Eau Claire' 'Green Bay' 'La Crosse' 'Madison'
 'Menomonie' 'Milwaukee' 'Oshkosh' 'Platteville' 'River Falls'
 'Stevens Point' 'Waukesha' 'Whitewater']

In [16]:
df_final=pd.DataFrame([])
StateName=np.append(StateName,'Wyoming')
city_new=np.append(city_new, 'Laramie')
df_final['State']=StateName
df_final['RegionName']=city_new
print(df_final)

         State     RegionName
0      Alabama         Auburn
1      Alabama       Florence
2      Alabama   Jacksonville
3      Alabama     Livingston
4      Alabama     Montevallo
..         ...            ...
512  Wisconsin    River Falls
513  Wisconsin  Stevens Point
514  Wisconsin       Waukesha
515  Wisconsin     Whitewater
516    Wyoming        Laramie

[517 rows x 2 columns]

In [15]:
len(city_new),len(StateName),len(df_final)

(517, 517, 517)

In [17]:
df_final.set_index(['State','RegionName'],inplace=True)

In [18]:
df_final.head(20)

Empty DataFrame
Columns: []
Index: [(Alabama, Auburn), (Alabama, Florence), (Alabama, Jacksonville), (Alabama, Livingston), (Alabama, Montevallo), (Alabama, Troy), (Alabama, Tuscaloosa), (Alabama, Tuskegee), (Alaska, Fairbanks), (Arizona, Flagstaff), (Arizona, Tempe), (Arizona, Tucson), (Arkansas, Arkadelphia), (Arkansas, Conway), (Arkansas, Fayetteville), (Arkansas, Jonesboro), (Arkansas, Magnolia), (Arkansas, Monticello), (Arkansas, Russellville), (Arkansas, Searcy)]

## Examples: University Towns in Kansas and Delaware

In [19]:
df_final.loc['Kansas']

Empty DataFrame
Columns: []
Index: [Baldwin City, Emporia, Hays, Lawrence, Manhattan, Pittsburg]

In [20]:
df_final.loc['Delaware']

Empty DataFrame
Columns: []
Index: [Dover, Newark]

## Number of University Towns in given state

In [21]:
df_final.reset_index().groupby('State').count()

                RegionName
State
Alabama                  8
Alaska                   1
Arizona                  3
Arkansas                 8
California              25
Colorado                 9
Connecticut              7
Delaware                 2
Florida                 12
Georgia                 16
Hawaii                   1
Idaho                    3
Illinois                10
Indiana                 13
Iowa                    13
Kansas                   6
Kentucky                11
Louisiana                8
Maine                    9
Maryland                10
Massachusetts           19
Michigan                20
Minnesota               14
Mississippi              5
Missouri                 9
Montana                  3
Nebraska                 7
Nevada                   2
New Hampshire            7
New Jersey              10
New Mexico               5
New York                31
North Carolina          18
North Dakota             2
Ohio                    22
Oklahoma                11
Oregon                  10
Pennsylvania            43
Rhode Island             2
South Carolina          11
South Dakota             4
Tennessee               13
Texas                   22
Utah                     6
Vermont                  6
Virginia                12
Washington               5
West Virginia            9
Wisconsin               13
Wyoming                  1